import{S as m,i as u}from"./assets/vendor-8c59ed88.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();function d(a){return a.map(e=>`<li class="photo-item">
        <a href="${e.largeImageURL}"><img class="img-item" src="${e.webformatURL}" alt="${e.tags}"/></a> 
        <div class="descr-wrapper">
        <p class="descr"><span class='label-img'>Likes</span> ${e.likes}</p>
        <p class="descr"><span class='label-img'>Views</span> ${e.views}</p>
        <p class="descr"><span class='label-img'>Comments</span> ${e.comments}</p>
        <p class="descr"><span class='label-img'>Downloads</span> ${e.downloads}</p>
        </div>
      </li>`).join("")}function p(a){const s=new URLSearchParams({key:"45320962-957458a2920d861910609dde6",q:`${a.value.trim()}`,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`https://pixabay.com/api/?${s}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const f=document.querySelector("#searchForm"),c=document.querySelector("#searchImg"),l=document.querySelector(".list-images"),n=document.querySelector(".loader"),g=new m(".list-images a",{captionsData:"alt",captionDelay:250});f.addEventListener("submit",a=>{a.preventDefault(),l.innerHTML="",n.style.display="block",p(c).then(s=>{if(s.hits.length===0){setTimeout(()=>{u.error({timeout:2500,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n.style.display="none"},3e3);return}else setTimeout(()=>{const e=d(s.hits);l.innerHTML=e,n.style.display="none",g.refresh()},1500)}).catch(s=>{console.log(s)}),c.value=""});
//# sourceMappingURL=commonHelpers.js.map
