import{a as L,S as b,i as l}from"./assets/vendor-8cd2069d.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const m of a.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&o(m)}).observe(document,{childList:!0,subtree:!0});function s(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(t){if(t.ep)return;t.ep=!0;const a=s(t);fetch(t.href,a)}})();function y(r){return r.map(s=>`<li class="photo-item">
        <a href="${s.largeImageURL}"><img class="img-item" src="${s.webformatURL}" alt="${s.tags}"/></a> 
        <div class="descr-wrapper">
        <p class="descr"><span class='label-img'>Likes</span> ${s.likes}</p>
        <p class="descr"><span class='label-img'>Views</span> ${s.views}</p>
        <p class="descr"><span class='label-img'>Comments</span> ${s.comments}</p>
        <p class="descr"><span class='label-img'>Downloads</span> ${s.downloads}</p>
        </div>
      </li>`).join("")}const f=async(r,e=1)=>{let s=15;const o=new URLSearchParams({key:"45320962-957458a2920d861910609dde6",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:e});return(await L.get(`https://pixabay.com/api/?${o}`)).data},w=document.querySelector("#searchForm"),g=document.querySelector("#searchImg"),d=document.querySelector(".list-images"),n=document.querySelector(".loader"),i=document.querySelector("#moreBtn"),h=new b(".list-images a",{captionsData:"alt",captionDelay:250});let p=1,c=0,u="";w.addEventListener("submit",r=>{r.preventDefault(),d.innerHTML="",n.style.display="block",u=g.value.trim(),p=1,f(u).then(e=>{if(e.totalHits,e.hits.length===0){l.error({timeout:2500,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n.style.display="none",i.style.display="none";return}else{const s=y(e.hits);d.innerHTML=s,c=e.hits.length,i.style.display=e.totalHits>e.hits.length?"flex":"none",n.style.display="none",h.refresh(),console.log(c)}}).catch(e=>{l.error({timeout:2500,position:"topRight",message:`Error: ${e.message||"Something went wrong"}`}),n.style.display="none",i.style.display="none"}),g.value=""});i.addEventListener("click",()=>{p+=1,n.style.display="block",i.style.display="none",f(u,p).then(r=>{if(c>=r.totalHits){l.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.style.display="none";return}c+=r.hits.length;const e=y(r.hits);d.insertAdjacentHTML("beforeend",e),h.refresh(),n.style.display="none",i.style.display="flex";const o=document.querySelector(".photo-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}).catch(r=>{l.error({timeout:2500,position:"topRight",message:`Error: ${r.message||"Something went wrong"}`}),n.style.display="none",i.style.display="flex"})});
//# sourceMappingURL=commonHelpers.js.map
