import{a as L,S as b,i as y}from"./assets/vendor-8cd2069d.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const l of a.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&o(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=s(e);fetch(e.href,a)}})();function g(r){return r.map(s=>`<li class="photo-item">
        <a href="${s.largeImageURL}"><img class="img-item" src="${s.webformatURL}" alt="${s.tags}"/></a> 
        <div class="descr-wrapper">
        <p class="descr"><span class='label-img'>Likes</span> ${s.likes}</p>
        <p class="descr"><span class='label-img'>Views</span> ${s.views}</p>
        <p class="descr"><span class='label-img'>Comments</span> ${s.comments}</p>
        <p class="descr"><span class='label-img'>Downloads</span> ${s.downloads}</p>
        </div>
      </li>`).join("")}const f=async(r,t=1)=>{let s=15;const o=new URLSearchParams({key:"45320962-957458a2920d861910609dde6",q:`${r}`,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:t});return(await L.get(`https://pixabay.com/api/?${o}`)).data},v=document.querySelector("#searchForm"),u=document.querySelector("#searchImg"),c=document.querySelector(".list-images"),n=document.querySelector(".loader"),i=document.querySelector("#moreBtn"),h=new b(".list-images a",{captionsData:"alt",captionDelay:250});let p=1,m=0,d="";v.addEventListener("submit",r=>{r.preventDefault(),c.innerHTML="",n.style.display="block",d=u.value.trim(),f(d).then(t=>{if(t.totalHits,t.hits.length===0){y.error({timeout:2500,position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n.style.display="none";return}else{const s=g(t.hits);c.innerHTML=s,m=t.hits.length,n.style.display="none",h.refresh(),i.style.display="flex"}}).catch(t=>{console.log(t)}),u.value=""});i.addEventListener("click",()=>{p+=1,n.style.display="block",i.style.display="none",f(d,p).then(r=>{if(m+=r.hits.length,m>=r.totalHits){y.error({position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.style.display="none";return}const t=g(r.hits);c.insertAdjacentHTML("beforeend",t),h.refresh(),n.style.display="none",i.style.display="flex";const o=document.querySelector(".photo-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}).catch(r=>{console.log(r),n.style.display="none"})});
//# sourceMappingURL=commonHelpers.js.map
